FROM python:3.11-slim

WORKDIR /app

RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        libpq-dev \
    && rm -rf /var/lib/apt/lists/*


COPY pyproject.toml .

COPY content_api/ content_api/
COPY models_api/ models_api/
COPY migrations/ migrations/

RUN pip install --upgrade pip \
 && pip install --no-cache-dir .\
 && pip install --no-cache-dir .[test]

COPY entrypoint.flask.sh /entrypoint.flask.sh
RUN chmod +x /entrypoint.flask.sh

EXPOSE 5000

# entrypoint runs migrations then starts Flask
CMD ["/entrypoint.flask.sh"]
