"""empty message

Revision ID: 0d3a351ec57b
Revises: 3410e8b3f3b1
Create Date: 2026-08-26 22:24:50.198405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d3a351ec57b'
down_revision = '3410e8b3f3b1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('publication_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_name', sa.VARCHAR(length=20), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
