"""Added publication_name column to db_article_model

Revision ID: 3410e8b3f3b1
Revises: c2bc260f781d
Create Date: 2026-08-26 16:59:42.741238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3410e8b3f3b1'
down_revision = 'c2bc260f781d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_name', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('publication_name')

    # ### end Alembic commands ###
