"""Added Image S3 Object Pydantic & DB model

Revision ID: 371db2142618
Revises: 0d3a351ec57b
Create Date: 2026-08-31 00:48:42.430365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '371db2142618'
down_revision = '0d3a351ec57b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('featured_image_key', sa.String(), nullable=False),
    sa.Column('labels', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
