"""Fixed Cascade

Revision ID: 5f25f373c4fd
Revises: 371db2142618
Create Date: 2026-08-31 09:20:30.899786

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f25f373c4fd'
down_revision = '371db2142618'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('images_article_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'articles', ['article_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('images_article_id_fkey'), 'publications', ['article_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
