"""Comprehend Integration - Added TagExtraction Imports

Revision ID: e3543d09dbb5
Revises: 3fce8adb1b4b
Create Date: 2026-09-01 14:27:16.807075

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'e3543d09dbb5'
down_revision = '3fce8adb1b4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tagextraction',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('article_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('tags', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('entities', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('tag_extraction')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag_extraction',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.Column('entities', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], name=op.f('tag_extraction_article_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('tag_extraction_pkey'))
    )
    op.drop_table('tagextraction')
    # ### end Alembic commands ###
