"""Added image constraint - 1 image per Article - Fixed Bug

Revision ID: e7b38531b6c5
Revises: 2c5cfd10b07f
Create Date: 2026-09-03 15:21:29.934395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7b38531b6c5'
down_revision = '2c5cfd10b07f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('images_featured_image_key_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['article_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('images', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('images_featured_image_key_key'), ['featured_image_key'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
